---
# vim: ts=2 sw=2 et ft=yaml.ansible

- name: load gitlab package dependency list based on distribution type
  include_vars: '{{ item }}'
  loop:
    - 'gitlab_pkg_dependencies.yml'
  tags:
    - 'gitlab_vars'

- name: install gitlab and dependencies
  import_tasks: install.yml
  tags:
    - 'gitlab_install'

- name: configure gitlab
  import_tasks: configure.yml
  tags:
    - 'gitlab_configure'
